#!/bin/bash

# Documentation Consolidation Script
# Removes redundant optimization documentation files while keeping essential information

echo "🔧 Starting documentation consolidation..."

# Create backup directory
BACKUP_DIR="optimization_docs_backup_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"

# List of essential files to keep
ESSENTIAL_FILES=(
    "OPTIMIZATION_GUIDE.md"  # Our new consolidated guide
    "README.md"
    "blueprint.md"
    "ROADMAP.md"
    "AGENTS.md"
    "task.md"
    "bug.md"
    "coding_standard.md"
)

# Array of redundant files to move to backup
REDUNDANT_FILES=(
    "ADVANCED_EDGE_OPTIMIZATION_IMPLEMENTATION.md"
    "ADVANCED_EDGE_PERFORMANCE_OPTIMIZATIONS.md"
    "ADVANCED_EDGE_PERFORMANCE_OPTIMIZATION_IMPLEMENTATION.md"
    "ADVANCED_EDGE_SUPABASE_OPTIMIZATION.md"
    "ADVANCED_EDGE_SUPABASE_OPTIMIZATION_SUMMARY.md"
    "ADVANCED_OPTIMIZATIONS_IMPLEMENTATION.md"
    "ADVANCED_OPTIMIZATION_IMPLEMENTATION.md"
    "ADVANCED_PERFORMANCE_OPTIMIZATIONS_V2.md"
    "ADVANCED_VERCEL_SUPABASE_OPTIMIZATION.md"
    "ADVANCED_VERCEL_SUPABASE_OPTIMIZATION_NEW.md"
    "BACKEND_OPTIMIZATIONS_COMPLETE.md"
    "BACKEND_OPTIMIZATIONS_SUMMARY.md"
    "BACKEND_OPTIMIZATIONS_SUMMARY_NEW.md"
    "BACKEND_OPTIMIZATION_FEATURES.md"
    "BACKEND_OPTIMIZATION_SUMMARY.md"
    "COMPREHENSIVE_BACKEND_OPTIMIZATION_SUMMARY.md"
    "CRITICAL_OPTIMIZATIONS_IMPLEMENTATION.md"
    "CRITICAL_OPTIMIZATIONS_SUMMARY.md"
    "DB_OPTIMIZATIONS.md"
    "DECEMBER_2024_OPTIMIZATION_IMPLEMENTATION.md"
    "DECEMBER_2024_OPTIMIZATION_SUMMARY.md"
    "DECEMBER_OPTIMIZATION_SUMMARY.md"
    "DECEMBER_PERFORMANCE_OPTIMIZATION.md"
    "EDGE_OPTIMIZATION_IMPLEMENTATION.md"
    "EDGE_OPTIMIZATION_IMPLEMENTATION_FINAL.md"
    "EDGE_OPTIMIZATION_IMPLEMENTATION_NEW.md"
    "EDGE_SUPABASE_OPTIMIZATION_IMPLEMENTATION.md"
    "EDGE_SUPABASE_OPTIMIZATION_NEW.md"
    "EDGE_SUPABASE_OPTIMIZATION_SUMMARY.md"
    "ENHANCED_BACKEND_OPTIMIZATIONS.md"
    "ENHANCED_EDGE_OPTIMIZATION.md"
    "ENHANCED_EDGE_OPTIMIZATION_NEW.md"
    "ENHANCED_EDGE_SUPABASE_OPTIMIZATION.md"
    "ENHANCED_PERFORMANCE_OPTIMIZATIONS.md"
    "ENHANCED_VERCEL_EDGE_OPTIMIZATION.md"
    "ENHANCED_VERCEL_SUPABASE_OPTIMIZATION.md"
    "FRONTEND_OPTIMIZATIONS_DOCS.md"
    "FRONTEND_OPTIMIZATIONS_SUMMARY.md"
    "FRONTEND_PERFORMANCE_OPTIMIZATIONS.md"
    "IMPLEMENTED_BACKEND_OPTIMIZATIONS.md"
    "LATEST_OPTIMIZATION_IMPLEMENTATION.md"
    "NEW_PERFORMANCE_OPTIMIZATIONS.md"
    "OPTIMIZATIONS.md"
    "OPTIMIZATION_IMPLEMENTATION_SUMMARY.md"
    "PERFORMANCE_OPTIMIZATIONS.md"
    "PERFORMANCE_OPTIMIZATIONS_V1.7.md"
    "PERFORMANCE_OPTIMIZATIONS_V1.8.md"
    "PERFORMANCE_OPTIMIZATIONS_V1_7.md"
    "PERFORMANCE_OPTIMIZATION_DECEMBER_2024.md"
    "PERFORMANCE_OPTIMIZATION_IMPLEMENTATION.md"
    "PERFORMANCE_OPTIMIZATION_PHASE1.md"
    "PERFORMANCE_OPTIMIZATION_SUMMARY.md"
    "SEO_OPTIMIZATION.md"
    "SEO_OPTIMIZATION_IMPLEMENTATION.md"
    "SUPABASE_OPTIMIZATION_GUIDE.md"
    "VERCEL_EDGE_OPTIMIZATION_IMPLEMENTATION.md"
    "VERCEL_EDGE_OPTIMIZATION_IMPLEMENTATION_NEW.md"
    "VERCEL_EDGE_OPTIMIZATION_NEW.md"
    "VERCEL_EDGE_OPTIMIZATION_SUMMARY.md"
    "VERCEL_EDGE_OPTIMIZATION_SUMMARY_NEW.md"
    "VERCEL_EDGE_SUPABASE_OPTIMIZATION_IMPLEMENTATION.md"
    "VERCEL_EDGE_SUPABASE_OPTIMIZATION_NEW.md"
    "VERCEL_EDGE_SUPABASE_OPTIMIZATION_SUMMARY.md"
    "VERCEL_SUPABASE_OPTIMIZATION.md"
    "VERCEL_SUPABASE_OPTIMIZATION_DECEMBER_2024.md"
    "VERCEL_SUPABASE_OPTIMIZATION_IMPLEMENTATION.md"
    "VERCEL_SUPABASE_OPTIMIZATION_NEW.md"
    "VERCEL_SUPABASE_OPTIMIZATION_SUMMARY.md"
)

# Count current documentation files
CURRENT_DOCS=$(find . -name "*.md" -not -path "./node_modules/*" -not -path "./.git/*" | wc -l)
echo "📊 Current documentation files: $CURRENT_DOCS"

# Move redundant files to backup
REMOVED_COUNT=0
for file in "${REDUNDANT_FILES[@]}"; do
    if [ -f "$file" ]; then
        echo "📦 Moving $file to backup..."
        mv "$file" "$BACKUP_DIR/"
        ((REMOVED_COUNT++))
    fi
done

echo "✅ Moved $REMOVED_COUNT redundant files to backup folder: $BACKUP_DIR"

# Count remaining documentation files
REMAINING_DOCS=$(find . -name "*.md" -not -path "./node_modules/*" -not -path "./.git/*" -not -path "./$BACKUP_DIR/*" | wc -l)
echo "📊 Remaining documentation files: $REMAINING_DOCS"
echo "📈 Documentation reduction: $(($CURRENT_DOCS - $REMAINING_DOCS)) files removed"

# Show essential files that were kept
echo ""
echo "📚 Essential documentation files preserved:"
for file in "${ESSENTIAL_FILES[@]}"; do
    if [ -f "$file" ]; then
        echo "   ✅ $file"
    else
        echo "   ❌ $file (not found)"
    fi
done

echo ""
echo "🎉 Documentation consolidation complete!"
echo "💾 Backup location: $BACKUP_DIR"
echo "📖 New consolidated guide: OPTIMIZATION_GUIDE.md"